kjvm-objs := jem.o malloc.o cli.o mstats.o

# kjvm-objs := core/domain.o core/jem.o core/jemUPipe.o core/malloc.o core/jar.o \
#                core/thread.o core/load.o core/call.o core/libcache.o \
#                core/portal.o core/call.o core/exception_handler.o \
#		core/memfs.o core/sched.o core/symfind.o core/vmsupport.o \
#		dom0/zero.o dom0/zero_AtomicVariable.o dom0/zero_BootFS.o \
#		dom0/zero_CAS.o dom0/zero_Clock.o dom0/zero_ComponentManager.o \
#		dom0/zero_CPUManager.o dom0/zero_CPUState.o \
#		dom0/zero_Credential.o dom0/zero_Domain.o \
#		dom0/zero_DomainManager.o \
#               gc/gc.o gc/gc_alloc.o

kjvm-objs += core/stub.o

clean-files += malloc.mc mstats.acc malloc.c mstats.c jem.mc cli.acc jem.c cli.c

kjvm.o: $(kjvm-objs)
	$(LD) -r -o $@ $(kjvm-objs)

obj-$(CONFIG_JEM) += kjvm.o

EXTRA_CFLAGS += -Idrivers/embedded/kjvm/include -Idrivers/embedded/kcli -Idrivers/embedded/kcfg -Idrivers/embedded/ktst

$(obj)/malloc.mc: $(src)/core/malloc.c
	$(CPP) $(c_flags) $(src)/core/malloc.c > $(obj)/malloc.mc

$(obj)/jem.mc: $(src)/core/jem.c
	$(CPP) $(c_flags) $(src)/core/jem.c > $(obj)/jem.mc

$(obj)/mstats.acc: $(src)/aspects/mstats_acc.c
	$(CPP) $(c_flags) $(src)/aspects/mstats_acc.c > $(obj)/mstats.acc

$(obj)/cli.acc: $(src)/aspects/cli_acc.c
	$(CPP) $(c_flags) $(src)/aspects/cli_acc.c > $(obj)/cli.acc

$(obj)/malloc.c $(obj)/mstats.c: $(obj)/malloc.mc $(obj)/mstats.acc
	acc $(obj)/malloc.mc $(obj)/mstats.acc

$(obj)/jem.c $(obj)/cli.c: $(obj)/jem.mc $(obj)/cli.acc
	acc $(obj)/jem.mc $(obj)/cli.acc

