kjvm-objs := core/jem.o core/malloc.o 

# kjvm-objs := core/domain.o core/jem.o core/jemUPipe.o core/malloc.o core/jar.o \
#                core/thread.o core/load.o core/call.o core/libcache.o \
#                core/portal.o core/call.o core/exception_handler.o \
#		core/memfs.o core/sched.o core/symfind.o core/vmsupport.o \
#		dom0/zero.o dom0/zero_AtomicVariable.o dom0/zero_BootFS.o \
#		dom0/zero_CAS.o dom0/zero_Clock.o dom0/zero_ComponentManager.o \
#		dom0/zero_CPUManager.o dom0/zero_CPUState.o \
#		dom0/zero_Credential.o dom0/zero_Domain.o \
#		dom0/zero_DomainManager.o \
#               gc/gc.o gc/gc_alloc.o

kjvm-objs += core/stub.o

clean-files += malloc.mc MallocStatistics.acc malloc.c MallocStatistics.c

kjvm.o: $(kjvm-objs)
	$(LD) -r -o $@ $(kjvm-objs)

obj-$(CONFIG_JEM) += kjvm.o

EXTRA_CFLAGS += -Idrivers/embedded/kjvm/include -Idrivers/embedded/kcli -Idrivers/embedded/kcfg -Idrivers/embedded/ktst

$(obj)/malloc.mc: $(src)/core/malloc_mc.c
	$(CPP) $(c_flags) $(src)/core/malloc_mc.c > $(obj)/malloc.mc

$(obj)/MallocStatistics.acc: $(src)/core/MallocStatistics_acc.c
	$(CPP) $(c_flags) $(src)/core/MallocStatistics_acc.c > $(obj)/MallocStatistics.acc

$(obj)/malloc.c $(obj)/MallocStatistics.c: $(obj)/malloc.mc $(obj)/MallocStatistics.acc
	acc $(obj)/malloc.mc $(obj)/MallocStatistics.acc

